# -*- coding: utf-8 -*-
"""TEXT TO IMAGE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kHZdu1C-tKClaOt7Gwbbw2qgB4b0h2P
"""

!pip install --upgrade diffusers transformers -q

from pathlib import Path
import tqdm
import torch
import pandas as pd
import numpy as np
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import cv2

from google.colab import output
output.enable_custom_widget_manager()

from huggingface_hub import notebook_login
notebook_login()

class CFG:
    device = "cuda"
    seed = 42
    generator = torch.Generator(device).manual_seed(seed)
    image_gen_steps = 35
    image_gen_model_id = "stabilityai/stable-diffusion-2"
    image_gen_size = (400,400)
    image_gen_guidance_scale = 9
    prompt_gen_model_id = "gpt2"
    prompt_dataset_size = 6
    prompt_max_length = 12

image_gen_model = StableDiffusionPipeline.from_pretrained(
    CFG.image_gen_model_id, torch_dtype=torch.float16,
    variant="fp16")
image_gen_model = image_gen_model.to(CFG.device)

experimental_pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2",use_auth_token=True)

device =torch.device("cuda")
experimental_pipe = experimental_pipe.to(device)

def generate_image(prompt, model):
    image = model(
        prompt, num_inference_steps=CFG.image_gen_steps,
        generator=CFG.generator,
        guidance_scale=CFG.image_gen_guidance_scale
    ).images[0]

    image = image.resize(CFG.image_gen_size)
    return image

generate_image("earth in space", image_gen_model)